[package]
name = "zconqueror"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[dependencies]
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "3d6d49d" }
origami = { git = "https://github.com/dojoengine/origami", tag = "v0.5.1" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.5.1" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
# Devnet
rpc_url = "http://localhost:5050/"
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
# Slot
# rpc_url = "https://api.cartridge.gg/x/zconqueror/katana"
# account_address = "0x603e42dd660816a9e5c2fc935633018db30df30764d452e6b4064700bc8e6e0"
# private_key = "0x4fd0675d3ec5e0d035c213de935696cdd1284d79525cd3275d24626c32825e7"
