[package]
cairo-version = "2.4.0"
name = "zconqueror"
version = "0.0.0"
edition = "2023_10"

[cairo]
sierra-replace-ids = true

[dependencies]
origami = { git = "https://github.com/dojoengine/origami", tag = "v0.6.0" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[scripts]
deploy-dev = "sozo --profile dev build && sozo --profile dev migrate plan && sozo --profile dev migrate apply && ./scripts/authorize.sh dev"
deploy-slot = "sozo --profile slot build && sozo --profile slot migrate plan --name v0 && sozo --profile slot migrate apply --name v0 && ./scripts/authorize.sh slot"
deploy-realms = "sozo --profile realms build && sozo --profile realms migrate plan --name v0 && sozo --profile realms migrate apply --name v0 && ./scripts/authorize.sh realms"
deploy-sepolia = "rm -rf ./manifest/sepolia && sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate plan --name zklash-v0 && sozo --profile sepolia migrate apply --fee-estimate-multiplier 10 --name zklash-v0 && ./scripts/authorize.sh sepolia"

# Katana
[profile.dev.tool.dojo.env]
rpc_url = "http://localhost:5050"
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

# Slot
[profile.slot.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/zconqueror/katana"
account_address = "0x74760fa19c8db4ce5cdc4b9e195edaf74910a4164047133c9fe83f584befc35"
private_key = "0x253d0d1cbcd524a7425eaa6bd67919f6104c03e2675161d9edd6b48fee0011b"

# Sepolia
[profile.sepolia.tool.dojo.env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_6"
#rpc_url = "https://free-rpc.nethermind.io/sepolia-juno/v0_6"
# account_address = 
# private_key = 

# Realms
[profile.realms.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/realms/katana/"
account_address = "0x251a85f6f4aaf609c69adc2940c0977b67a5f50c57affdba6a8a0682bd543a4"
private_key = "0x46d907d74b2f91acbcb8f29e76ad844325edd66a3896ab18bbe42f8cb235591"

[tool.dojo.world]
name = "zConqueror"
description = "Onchain Risk-like game: dominate the map, defend your realm, win rewards."
icon_uri = "https://ibb.co/GtSyhCt"
cover_uri = "https://ibb.co/HqKYhLH"
website = "https://app.zconqueror.xyz"

[tool.dojo.world.socials]
x = "https://x.com/zKorp_"
github = "https://github.com/z-korp"