[package]
cairo-version = "2.2.0"
name = "zconqueror"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=2.2.0"
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "d32162a" }
origami = { git = "https://github.com/dojoengine/origami", rev = "e873a5a" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.4.4" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
