blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://github.com/Risk-Labs/zrisk-contracts#contribution
    about: This issue tracker is only for bugs and feature requests. Support is available through other communication channels.