[book]
authors = ["Z-Labs"]
language = "en"
multilingual = false
src = "src"
title = "zRisk Book"

[output.html]
git-repository-url = "https://github.com/risk-labs/zrisk-contracts/"
edit-url-template = "https://github.com/risk-labs/zrisk-contracts/book/{path}"

[output.html.playground]
runnable = false